### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by daledali** [smahesh29/File-Sorter#1]
How does it work?

**Comment by smahesh29** [comment]
Keep the files you wants to sort in Download folder. After running the program 
`python File_sorter.py,` it will move the files from Download folder to the folders Applications, Codes, Images, Others, Sounds, Text, Videos depends on the type of file.

**Comment by 21Z** [comment]
run it and a person will come to ur house and he will fuck ur mom. thats how it works
